export const styles = {
    confirm_box: {
        position: "absolute",
        zIndex: "20",
        backgroundColor: "#515151",
        border: "1px solid #5d5d5d",
    },
    yes_button: {
        position: "absolute",
        zIndex: "inherit",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: "#b6b6b6",
        backgroundColor: "#5d5d5d",
        border: "1px solid #454849",
        overflow: "hidden",
        textOverflow: "ellipsis",
        cursor: "pointer",
    },
    yes_button_hover: {
        color: "#515151",
        backgroundColor: "#b6b6b6",
    },
    no_button: {
        position: "absolute",
        zIndex: "inherit",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: "#b6b6b6",
        backgroundColor: "#5d5d5d",
        border: "1px solid #454849",
        overflow: "hidden",
        textOverflow: "ellipsis",
        cursor: "pointer",
    },
    no_button_hover: {
        color: "#515151",
        backgroundColor: "#b6b6b6",
    },
    label1: {
        position: "absolute",
        zIndex: "inherit",
        width: "100%",
        top: "0%",
        height: "10%",
        color: "#b6b6b6",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        fontSize: "180%",
        paddingTop: "8px",
        textAlign: "center",
    },
    piece_name: {
        position: "absolute",
        zIndex: "inherit",
        top: "35%",
        width: "100%",
        height: "30%",
        textAlign: "center",
        overflow: "hidden",
        textOverflow: "ellipsis",
        color: "#b6b6b6",
        fontSize: "180%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    },
    label2: {
        position: "absolute",
        zIndex: "inherit",
        top: "65%",
        width: "100%",
        height: "20%",
        color: "#b6b6b6",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        fontSize: "180%",
        paddingTop: "8px",
        textAlign: "center",
    },
};
