export const styles = {
    help_modal: {
        position: "fixed",
        zIndex: "9",
        left: "0",
        top: "0",
        width: "100%",
        height: "100%",
        backgroundColor: "#0000004d",
    },
    help_modal_window: {
        position: "relative",
        zIndex: "10",
        width: "768px",
        left: "384px",
        top: "75px",
        display: "grid",
        MsGridRows: "30px 354px 45px",
        gridTemplateRows: "30px 354px 45px",
        MsGridColumns: "768px",
        gridTemplateColumns: "768px",
        borderRadius: "15px",
        border: "5px solid #707070",
        backgroundColor: "#515151",
    },
    help_modal_window_top: {
        position: "absolute",
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
        backgroundColor: "#515151",
        borderTopLeftRadius: "8px",
        borderTopRightRadius: "8px",
        display: "grid",
        MsGridRows: "30px",
        gridTemplateRows: "30px",
        MsGridColumns: "752px 8px",
        gridTemplateColumns: "752px 8px",
    },
    help_modal_window_title: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        fontSize: "20px",
        color: "#b6b6b6",
        backgroundColor: "#515151",
    },
    help_modal_window_close: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        width: "15px",
        height: "15px",
        cursor: "pointer",
    },
    help_modal_window_close_hover: {
        backgroundColor: "#EC2525",
    },
    help_modal_window_text_area: {
        MsGridColumn: "1",
        gridColumn: "1",
        MsGridRow: "2",
        gridRow: "2",
        color: "#b6b6b6",
        backgroundColor: "#515151",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        fontSize: "15px",
        paddingLeft: "23px",
        paddingRight: "23px",
        paddingTop: "8px",
        paddingBottom: "23px",
        borderBottomLeftRadius: "8px",
        borderBottomRightRadius: "8px",
        wordWrap: "break-word",
        overflowY: "scroll",
    },
    help_modal_window_bottom: {
        MsGridRow: "3",
        gridRow: "3",
        MsGridColumn: "1",
        gridColumn: "1",
        backgroundColor: "#515151",
    },
    help_modal_window_bottom_button: {
        position: "relative",
        width: "60px",
        height: "25px",
        left: "353px",
        top: "8px",
        textAlign: "center",
        paddingTop: "2px",
        fontSize: "13px",
        color: "#b6b6b6",
        backgroundColor: "#707070",
        border: "#707070",
        borderRadius: "4px",
        cursor: "pointer",
    },
    help_modal_window_bottom_button_hover: {
        backgroundColor: "#b6b6b6",
        color: "#515151",
    },
};
