export const styles = {
    message_modal: {
        position: "fixed",
        zIndex: "10",
        left: "0",
        top: "0",
        width: "100%",
        height: "100%",
        backgroundColor: "#0000004d",
    },
    message_modal_window: {
        position: "absolute",
        zIndex: "20",
        backgroundColor: "#515151",
        border: "1px solid #5d5d5d",
    },
    message_modal_window__msg_title: {
        position: "absolute",
        zIndex: "inherit",
        width: "90%",
        height: "10%",
        left: "5%",
        top: "5%",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        fontSize: "160%",
        color: "#b6b6b6",
        backgroundColor: "#515151",
        wordWrap: "break-word",
    },
    message_modal_window__msg_text: {
        position: "absolute",
        top: "45%",
        left: "5%",
        width: "90%",
        height: "50%",
        zIndex: "inherit",
        color: "#b6b6b6",
        backgroundColor: "#515151",
        fontSize: "145%",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        textAlign: "center",
        wordWrap: "break-word",
        overflowY: "hidden",
        textOverflow: "ellipsis",
    },
    message_modal_window__msg_ok_button: {
        top: "90%",
        left: "55%",
        position: "absolute",
        zIndex: "inherit",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: "#b6b6b6",
        backgroundColor: "#5d5d5d",
        border: "1px solid #454849",
        overflow: "hidden",
        textOverflow: "ellipsis",
        cursor: "pointer",
    },
    message_modal_window__msg_ok_button_hover: {
        color: "#515151",
        backgroundColor: "#b6b6b6",
    },
    message_modal_window__msg_modal_close: {
        position: "absolute",
        cursor: "pointer",
        left: "95%",
        top: "2%",
        width: "5%",
        height: "5%",
    },
    message_modal_window__msg_modal_close_hover: {
        backgroundColor: "#EC2525",
    },
};
