version: "3"
services:
  frontend:
    container_name: react_frontend
    build:
      context: ./react_frontend
      dockerfile: ./react_frontend/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: python_backend
    build: ./python_backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1