export const styles = {
    image_choices__image_choice_container: {
        zIndex: "2",
        width: "100%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        borderRadius: "5px",
        textAlign: "center",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        cursor: "pointer",
    },
    image_choices__selected_image_choice_container: {
        zIndex: "2",
        width: "100%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        borderRadius: "5px",
        textAlign: "center",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        cursor: "pointer",
        WebkitBoxShadow: "0px 0px 16px white",
        boxShadow: "0px 0px 16px white",
        color: "white",
    },
    image_choices__image_choice: {
        position: "relative",
        width: "95%",
        maxHeight: "95%",
        margin: "2.5%",
    },
    image_choices__piece_name: {
        position: "relative",
        top: "-8%",
        width: "100%",
        height: "7.5%",
        color: "#72e2ff",
        textAlign: "center",
        overflow: "hidden",
        textOverflow: "ellipsis",
    },
};
