export const styles = {
    invalid_game_name_modal: {
        position: "fixed",
        zIndex: "3",
        top: "0",
        width: "100%",
        height: "100%",
        backgroundColor: "#0000004d",
    },
    invalid_game_name_window: {
        position: "absolute",
        zIndex: "inherit",
        left: "460px",
        top: "226px",
        width: "598px",
        height: "302px",
        backgroundColor: "#515151",
        border: "1px solid #b6b6b6",
        borderRadius: "10px",
    },
    invalid_game_name_heading: {
        position: "absolute",
        zIndex: "inherit",
        top: "40px",
        width: "598px",
        color: "#b6b6b6",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        fontSize: "16px",
        textAlign: "center",
        wordWrap: "break-word",
    },
    invalid_game_name_button: {
        position: "absolute",
        zIndex: "inherit",
        left: "246px",
        top: "258px",
        height: "30px",
        width: "90px",
        fontSize: "16px",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        textAlign: "center",
        paddingTop: "3px",
        color: "#b6b6b6",
        backgroundColor: "#606060",
        border: "1px solid #606060",
        borderRadius: "5px",
        cursor: "pointer",
    },
    invalid_game_name_button_hover: {
        color: "#606060",
        backgroundColor: "#b6b6b6",
        border: "1px solid #b6b6b6",
    },
};
