export const styles = {
    tools_menu: {
        position: "absolute",
    },
    tools_menu_name: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "0",
    },
    tools_menu_icon: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "16%",
    },
    tools_menu_range: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "32%",
    },
    tools_menu_location: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "48%",
    },
    tools_menu_options: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "64%",
    },
    name_expand_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "0",
    },
    icon_expand_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "16%",
    },
    range_expand_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "32%",
    },
    location_expand_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "48%",
    },
    options_expand_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "64%",
    },
    tool_bar_selected: {
        position: "absolute",
        width: "100%",
        height: "16%",
        backgroundColor: "#515151",
        border: "1px solid #3c3f41",
        top: "32%",
    },
    tool_bar_selected_widget: {
        position: "absolute",
        left: "90%",
        height: "16%",
        width: "7.5%",
        top: "-2.5%",
    },
};
