export const dbSampleDefs = {
    "Bishop": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FBB.svg?alt=media&token=3ebbcac2-264f-4eea-9603-5346ce38a5d6",
            "spans": [
                "step_1sqr225d",
                "step_1sqr315d",
                "step_1sqr45d",
                "step_1sqr135d",
            ],
            "offsets": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FWB.svg?alt=media&token=8197220b-1c25-4fb4-8220-b68546fb1dba",
            "spans": [
                "step_1sqr45d",
                "step_1sqr135d",
                "step_1sqr225d",
                "step_1sqr315d",
            ],
            "offsets": [],
        },
    },
    "Docker": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fdocker-red.svg?alt=media&token=ed16a508-7509-41fc-af3e-2a75e7343f16",
            "offsets": [
                "2,-1",
                "0,-1",
                "1,-1",
                "-1,-1",
                "-2,-1",
                "1,-2",
                "0,-2",
                "-1,-2",
                "-1,-3",
                "0,1",
            ],
            "spans": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fdocker.svg?alt=media&token=ebdac6ad-c97d-41da-9c2b-d4f4810c420f",
            "offsets": [
                "-2,1",
                "0,1",
                "-1,1",
                "1,1",
                "2,1",
                "-1,2",
                "0,2",
                "1,2",
                "1,3",
                "0,-1",
            ],
            "spans": [],
        },
    },
    "Dragon": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fdragon-black.svg?alt=media&token=bf5e6a5c-18c7-4b4f-a209-42b63ae44990",
            "offsets": [
                "2,-1",
                "1,-2",
                "-1,-2",
                "-2,-1",
                "-2,1",
                "-1,2",
                "1,2",
                "2,1",
            ],
            "spans": [
                "step_1sqr270d",
                "step_1sqr225d",
                "step_1sqr180d",
                "step_1sqr135d",
                "step_1sqr90d",
                "step_1sqr45d",
                "step_1sqr0d",
                "step_1sqr315d",
            ],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fdragon-white.svg?alt=media&token=3e5a2970-e411-4190-a51a-ec40954beb86",
            "offsets": [
                "-2,1",
                "-1,2",
                "1,2",
                "2,1",
                "2,-1",
                "1,-2",
                "-1,-2",
                "-2,-1",
            ],
            "spans": [
                "step_1sqr90d",
                "step_1sqr45d",
                "step_1sqr0d",
                "step_1sqr315d",
                "step_1sqr270d",
                "step_1sqr225d",
                "step_1sqr180d",
                "step_1sqr135d",
            ],
        },
    },
    "Evil Morty": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fevil_morty_red.svg?alt=media&token=24b28ab7-892b-4ec0-a340-b2fbce12e02f",
            "offsets": ["0,1", "1,0", "-1,0", "0,-1"],
            "spans": [
                "step_1sqr225d",
                "step_1sqr135d",
                "step_1sqr45d",
                "step_1sqr315d",
            ],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fevil_morty_white.svg?alt=media&token=725d1a07-7078-47d6-a1bf-99114c3adf57",
            "offsets": ["0,-1", "-1,0", "1,0", "0,1"],
            "spans": [
                "step_1sqr45d",
                "step_1sqr315d",
                "step_1sqr225d",
                "step_1sqr135d",
            ],
        },
    },
    "Firelord": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fblack_firehat.svg?alt=media&token=ea2d8a52-0fb8-44be-b393-32d94f0e2c0d",
            "offsets": ["2,-1", "1,-2", "-1,-2", "-2,-1", "0,1"],
            "spans": [
                "step_1sqr270d",
                "step_1sqr225d",
                "step_1sqr180d",
                "step_1sqr0d",
                "step_1sqr315d",
            ],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fwhite_firehat.svg?alt=media&token=d67523d1-1800-458a-b73d-74f520bf3a25",
            "offsets": ["-2,1", "-1,2", "1,2", "2,1", "0,-1"],
            "spans": [
                "step_1sqr90d",
                "step_1sqr45d",
                "step_1sqr0d",
                "step_1sqr180d",
                "step_1sqr135d",
            ],
        },
    },
    "Knight": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FBN.svg?alt=media&token=22ea957a-0420-4709-885b-112f85e35a1b",
            "offsets": [
                "1,2",
                "1,-2",
                "-1,2",
                "-1,-2",
                "2,1",
                "2,-1",
                "-2,1",
                "-2,-1",
            ],
            "spans": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FWN.svg?alt=media&token=fba79c88-f13f-4c81-b701-eaa3c32111ad",
            "offsets": [
                "1,2",
                "1,-2",
                "-1,2",
                "-1,-2",
                "2,1",
                "2,-1",
                "-2,1",
                "-2,-1",
            ],
            "spans": [],
        },
    },
    "Material UI": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fmaterial-ui-red.svg?alt=media&token=b68155b4-500b-4523-a7f6-3d91a802c97b",
            "offsets": [
                "2,-3",
                "1,-2",
                "0,-1",
                "-1,-2",
                "-2,-3",
                "-2,-1",
                "2,0",
                "2,-1",
                "-3,0",
                "-4,-1",
                "-4,-3",
                "-2,0",
            ],
            "spans": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fmaterial-ui.svg?alt=media&token=c99c99b5-7f94-483b-9300-0aedc0d09a6b",
            "offsets": [
                "-2,3",
                "-1,2",
                "0,1",
                "1,2",
                "2,3",
                "2,1",
                "-2,0",
                "-2,1",
                "3,0",
                "4,1",
                "4,3",
                "2,0",
            ],
            "spans": [],
        },
    },
    "Node": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fnode-red.png?alt=media&token=5618891c-2e99-4cbd-9fda-56166755d429",
            "offsets": ["0,2", "1,1", "2,0", "1,-1", "0,-2", "-1,-1", "-2,0", "-1,1"],
            "spans": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fsample%20images%2Fnode-green.png?alt=media&token=ead36db1-554a-40fa-b329-c7b21db5a888",
            "offsets": ["0,-2", "-1,-1", "-2,0", "-1,1", "0,2", "1,1", "2,0", "1,-1"],
            "spans": [],
        }
    },
    "Queen": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FBQ.svg?alt=media&token=67f545b3-5a72-4b11-8333-2e74c9337e58",
            "spans": [
                "step_1sqr180d",
                "step_1sqr225d",
                "step_1sqr270d",
                "step_1sqr315d",
                "step_1sqr0d",
                "step_1sqr90d",
                "step_1sqr45d",
                "step_1sqr135d",
            ],
            "offsets": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FWQ.svg?alt=media&token=d52a7466-6e6e-48ad-8f70-2ceb7170477d",
            "spans": [
                "step_1sqr0d",
                "step_1sqr45d",
                "step_1sqr90d",
                "step_1sqr135d",
                "step_1sqr180d",
                "step_1sqr225d",
                "step_1sqr270d",
                "step_1sqr315d",
            ],
            "offsets": [],
        },
    },
    "Rook": {
        "B": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FBR.svg?alt=media&token=fe092c67-8327-492e-b3d5-601f70f2bb31",
            "spans": [
                "step_1sqr180d",
                "step_1sqr270d",
                "step_1sqr0d",
                "step_1sqr90d",
            ],
            "offsets": [],
        },
        "W": {
            "img": "https://firebasestorage.googleapis.com/v0/b/custom-chess.appspot.com/o/source%2Fstandard%20piece%20images%2FWR.svg?alt=media&token=60884e5c-e3cb-4a87-bc27-8902247e751d",
            "spans": [
                "step_1sqr0d",
                "step_1sqr90d",
                "step_1sqr180d",
                "step_1sqr270d",
            ],
            "offsets": [],
        },
    },
};