export const testUserImgs = [
    'anonomous-black.PNG',
    'anonomous-white.PNG',
    'BlackBishop.png',
    'BlackKing.png',
    'BlackKnight.png',
    'BlackPawn.png',
    'BlackQueen.png',
    'BlackRook.png',
    'dark-blue.png',
    'gold-node.png',
    'node-dark-green.png',
    'node-green.png',
    'node-pink.png',
    'node-purple.png',
    's-bishop.jpg',
    's-king.jpg',
    's-knight.jpg',
    's-pawn.jpg',
    's-queen.jpg',
    's-rook.jpg',
    'silver-node.png',
    'stary night.jpg',
    'stary sunset.jpg',
    'WhiteBishop.png',
    'WhiteKing.png',
    'WhiteKnight.png',
    'WhitePawn.png',
    'WhiteQueen.png',
    'WhiteRook.png',
    'white_blue_devil.png'
]