import React from "react";
import MenuItem from "@material-ui/core/MenuItem";
import {mechwarrior_theme} from "./mechwarrior_theme";

export const themes = {
    dark: {
        outline: '#2b2b2b',
        fill: '#3d3d3d',
        fill2: '#3d3d3d',
        text: '#a9a9a9',
        text_alt: '#707070',
        text_alt2: '#252525',
        text_alt3: '#aaaaaa',
        nav_text: '#252525',
        button_fill: '#414141',
        button_text: '#a9a9a9',
        button_hover_fill: '#444444',
        button_hover_text: '#a9a9a9',
        location_button_selected: '#4b6eaf',
        modal_fill: '#3f3f3f',
        img_border: '#2b2b2b',
        even_row: '#414141',
        odd_row: '#474747',
        span: '#ec2525',
        offset: '#a70000',
        span_alt: '#c60116',
        arrow_active: '#ff9e80',
        arrow_inactive: '#dc0000',
        light_normal: '#f0f0ff',
        dark_normal: '#a9a9b8',
        light_in_range: '#0081cb',
        dark_in_range: '#0081cb',
        sqr_text_light: '#a9a9a9',
        sqr_text_dark: '#ffffff',
        sqr_border: '#00CCff',
        sqr_text: '#ffccbc',
        sqr_hover: 'rgba(255, 255, 255, 0.2)',
        sqr_hover_alt: '#669df6',
        page_link: '#a9a9a9',
        page_link_hover: '#ffffff',
        drawer_outline: '#373737',
        switch_active: '#0081cb',
        variant_fill_r0: 157,
        variant_fill_g0: 80,
        variant_fill_b0: 226,
        variant_stroke_r0: 0,
        variant_stroke_g0: 0,
        variant_stroke_b0: 255,
        variant_fill_r1: 236,
        variant_fill_g1: 37,
        variant_fill_b1: 37,
        variant_stroke_r1: 157,
        variant_stroke_g1: 80,
        variant_stroke_b1: 120,
    },
    tan: {
        outline: '#2b2b2b',
        fill: '#000000',
        fill2: '#000000',
        text: '#d7bb99',
        text_alt: '#edc9a2ff',
        text_alt2: '#d7bb99',
        text_alt3: '#111111',
        nav_text: '#d7be9b',
        button_fill: '#1b1b1b',
        button_text: '#d7bb99',
        button_hover_fill: '#282828',
        button_hover_text: '#edc9a2ff',
        location_button_selected: '#4b6eaf',
        modal_fill: '#111111',
        img_border: '#d7bb99',
        even_row: '#1b1b1b',
        odd_row: '#252525',
        span: '#c60116',
        offset: '#990606',
        span_alt: '#c60116',
        arrow_active: '#ff8a80',
        arrow_inactive: '#b71c1c',
        light_normal: '#f0d9b5',
        dark_normal: '#d0bd99',
        light_in_range: '#fff172',
        dark_in_range: '#acaf4b',
        sqr_hover: '#60a8f0',
        sqr_text: '#ffccbc',
        sqr_hover_alt: '#60A8F0',
        page_link: '#000000',
        page_link_hover: '#ffffff',
        drawer_outline: '#373737',
        switch_active: '#d7bb99',
        variant_fill_r0: 157,
        variant_fill_g0: 80,
        variant_fill_b0: 226,
        variant_stroke_r0: 0,
        variant_stroke_g0: 0,
        variant_stroke_b0: 255,
        variant_fill_r1: 236,
        variant_fill_g1: 37,
        variant_fill_b1: 37,
        variant_stroke_r1: 157,
        variant_stroke_g1: 80,
        variant_stroke_b1: 120,
    },
    star_wars: {
        outline: '#f6b601',
        fill: '#000000',
        fill2: '#000000',
        text: '#f6b601',
        text_alt: '#ffe81e',
        text_alt2: 'goldenrod',
        text_alt3: '#fcbb04',
        nav_text: 'gold',
        button_fill: '#1b1b1b',
        button_text: '#f6b601',
        button_hover_fill: '#2b2b2b',
        button_hover_text: '#28ded3',
        location_button_selected: '#4b6eaf',
        modal_fill: '#111111',
        img_border: '#f6b601',
        even_row: '#1b1b1b',
        odd_row: '#252525',
        span: '#c60116',
        offset: '#990606',
        span_alt: '#c60116',
        arrow_active: '#ff645a',
        arrow_inactive: '#b71c1c',
        light_normal: '#ffe81e',
        dark_normal: 'rgba(0, 0, 0, 0)',
        light_in_range: '#fff172',
        dark_in_range: 'rgba(255, 241, 114, 0.5)',
        sqr_hover: '#60a8f0',
        sqr_text: '#ffccbc',
        sqr_hover_alt: '#60a8f0',
        page_link: '#ffe81e',
        page_link_hover: '#60a8f0',
        drawer_outline: '#373737',
        switch_active: '#28ded3',
        variant_fill_r0: 157,
        variant_fill_g0: 80,
        variant_fill_b0: 226,
        variant_stroke_r0: 0,
        variant_stroke_g0: 0,
        variant_stroke_b0: 255,
        variant_fill_r1: 236,
        variant_fill_g1: 37,
        variant_fill_b1: 37,
        variant_stroke_r1: 157,
        variant_stroke_g1: 80,
        variant_stroke_b1: 120,
    },
    mechwarrior_a_team: mechwarrior_theme,
    mechwarrior_b_team: mechwarrior_theme,
    NBA: {
        outline: '#ffffff',
        fill: '#253b73',
        fill2: '#b52532',
        text: '#ffffff',
        text_alt: '#ffffff',
        text_alt2: '#ffffff',
        text_alt3: '#ffffff',
        nav_text: '#ffffff',
        button_fill: '#253b73',
        button_text: '#ffffff',
        button_hover_fill: '#b52532',
        button_hover_text: '#ffffff',
        location_button_selected: '#253b73',
        modal_fill: '#b52532',
        img_border: '#ffffff',
        even_row: '#253b73',
        odd_row: '#b52532',
        span: '#b52532',
        offset: '#253b73',
        span_alt: '#ff0000',
        arrow_active: '#ff8a80',
        arrow_inactive: '#b71c1c',
        light_normal: 'rgba(255, 255, 255, 0.65)',
        dark_normal: 'rgba(0, 0, 0, 0)',
        light_in_range: 'rgba(181, 37, 50, 0.3)',
        dark_in_range: 'rgba(37, 59, 115, 0.3)',
        sqr_text_light: '#ffffff',
        sqr_text_dark: '#ffffff',
        sqr_border: 'rgba(255, 0, 0, 0.6)',
        sqr_text: '#ffccbc',
        sqr_hover: '#ff0000',
        sqr_hover_alt: '#72e2ff',
        page_link: '#ffffff',
        page_link_hover: '#ffffff',
        drawer_outline: '#373737',
        switch_active: '#cdcdcd',
        variant_fill_r0: 157,
        variant_fill_g0: 80,
        variant_fill_b0: 226,
        variant_stroke_r0: 0,
        variant_stroke_g0: 0,
        variant_stroke_b0: 255,
        variant_fill_r1: 236,
        variant_fill_g1: 37,
        variant_fill_b1: 37,
        variant_stroke_r1: 157,
        variant_stroke_g1: 80,
        variant_stroke_b1: 120,
    },
    /**
     * given so that can override styles elsewhere and don't need to worry about errors of the form:
     * 'cannot read property foo of undefined'
     */
    none: {
        outline: null,
        fill: null,
        checkmark: null,
        font: null,
        button_fill: null,
        button_text: null,
        button_hover_fill: null,
        button_hover_text: null,
    }
};

export const themeList = [
    'dark',
    'tan',
]

export const specialThemeList = [
    'star_wars',
    'mechwarrior_a_team',
    'mechwarrior_b_team',
    'NBA',
]

export const themesMenuItemList = [
    <MenuItem value="dark">dark</MenuItem>,
    <MenuItem value="tan">tan</MenuItem>,
];

export const specialThemeMenuItemList = [
    <MenuItem value="star_wars">Star Wars</MenuItem>,
    <MenuItem value="mechwarrior_a_team">MechWarrior A-Team</MenuItem>,
    <MenuItem value="mechwarrior_b_team">MechWarrior B-team</MenuItem>,
    <MenuItem value="NBA">NBA</MenuItem>,
]