type IdDict = {
    k: "King",
    p: "Pawn",
    q: string,
    r:string,
    b: string,
    n: string,
    a?: string,
    c?: string,
    d?: string,
    e?: string,
    f?: string,
    g?: string,
    h?: string,
    i?: string,
    j?: string,
    l?: string,
    m?: string,
    o?: string,
    s?: string,
    t?: string,
    u?: string,
    v?: string,
    w?: string,
    x?: string,
    y?: string,
    z?: string,
};
export default IdDict;