export const styles = {
    nav_bar__go_to_help: {
        MsGridColumn: "1",
        gridColumn: "1",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
    },
    nav_bar__go_to_home: {
        MsGridColumn: "2",
        gridColumn: "2",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
        zIndex: "10",
    },
    nav_bar__go_to_home__home_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_home__home_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_new_game: {
        MsGridColumn: "3",
        gridColumn: "3",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
        zIndex: "9",
    },
    nav_bar__go_to_new_game__new_game_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_new_game__new_game_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_load_game: {
        MsGridColumn: "4",
        gridColumn: "4",
        zIndex: "8",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_load_game__go_to_load_game_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_load_game__go_to_load_game_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_create_piece: {
        MsGridColumn: "5",
        gridColumn: "5",
        zIndex: "7",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_create_piece__create_piece_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_create_piece__create_piece_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_chess_rules: {
        MsGridColumn: "6",
        gridColumn: "6",
        zIndex: "6",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_chess_rules__chess_rules_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_chess_rules__chess_rules_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_council_rules: {
        MsGridColumn: "7",
        gridColumn: "7",
        zIndex: "5",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_council_rules__council_rules_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_council_rules__council_rules_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_my_pieces: {
        MsGridColumn: "8",
        gridColumn: "8",
        zIndex: "4",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_my_pieces__my_pieces_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_my_pieces__my_pieces_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },
    nav_bar__go_to_author_github: {
        MsGridColumn: "9",
        gridColumn: "9",
        zIndex: "3",
        cursor: "pointer",
        display: "grid",
        width: "100%",
        MsGridColumns: "25% 75%",
        gridTemplateColumns: "25% 75%",
        backgroundColor: "#515151",
        borderRight: "1px solid #707070",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        textDecoration: "none",
    },
    nav_bar__go_to_author_github__author_github_icon: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "1",
        gridColumn: "1",
    },
    nav_bar__go_to_author_github__author_github_text: {
        MsGridRow: "1",
        gridRow: "1",
        MsGridColumn: "2",
        gridColumn: "2",
        textAlign: "center",
        paddingTop: "8%",
        color: "#b6b6b6",
        fontSize: "140%",
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        wordwrap: "break-word",
    },    nav_bar_icon_style: {
        cursor: 'pointer',
        zIndex: '0',
        width: '80%',
        marginLeft: '13%',
        marginTop: '12%'
      },
};
