const test2Before = {
    "2FOctocat-black|,svg": 1,
    "2FOctocat-white|,svg": 1,
    "2Fblack_firehat|,svg": 2, //er: 3,
    "2Fdocker-red|,svg": 4, //er: 5,
    "2Fdocker|,svg": 4, //er: 5,
    "2Fdragon-black|,svg": 4, //er: 5,
    "2Fdragon-white|,svg": 4, //er: 5,
    "2Fevil_morty_blue|,svg": 1,
    "2Fevil_morty_red|,svg": 3, //er: 4,
    "2Fevil_morty_white|,svg": 3, //er: 4,
    "2Fmaterial-ui-red|,svg": 3, //er: 4,
    "2Fmaterial-ui|,svg": 3, //er: 4,
    "2Fnode-green|,png": 4, //er: 5,
    "2Fnode-red|,png": 4, //er: 5,
    "2Fwhite_firehat|,svg": 2, //er: 3,
    "2Fscream|,png": 2, //er: 3,
};
