export const styles = {
    my_load_button: {
        position: "absolute",
        zIndex: "inherit",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: "#b6b6b6",
        backgroundColor: "#5d5d5d",
        border: "1px solid #454849",
        overflow: "hidden",
        textOverflow: "ellipsis",
        cursor: "pointer",
        top: "22.5%",
        left: "86%",
    },
    my_load_button_hover: {
        color: "#515151",
        backgroundColor: "#b6b6b6",
    },
    my_delete_button: {
        position: "absolute",
        zIndex: "inherit",
        textAlign: "center",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: "#b6b6b6",
        backgroundColor: "#5d5d5d",
        border: "1px solid #454849",
        overflow: "hidden",
        textOverflow: "ellipsis",
        cursor: "pointer",
        top: "22.5%",
        left: "93%",
    },
    my_delete_button_hover: {
        color: "#515151",
        backgroundColor: "#b6b6b6",
    },
};
